version : 0.2
phases: 
  install:
    runtime-versions: 
      nodejs: 22.4
    commands:
      - echo "Installing dependencies...."
      - npm install
      - npm install -g @angular/cli@latest
  build:
    commands:
      - echo "building angular project...."
      - ng build --configuration production --aot
  post_build:  
    commands:
      - echo "updating files in s3 bucket..."
      - aws s3 sync dist/dream-share/browser s3://dreams-archive.com --delete